name: Build Tkinter App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Windows Executable
        run: |
          pyinstaller src/aurachat_helper_app/main.py --onefile --windowed --name aurachat_helper
          dir dist

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: aurachat_helper-windows
          path: dist/aurachat_helper.exe

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build macOS arm64 (Apple Silicon)
        run: |
          ARCHFLAGS='-arch arm64' pyinstaller src/aurachat_helper_app/main.py --onefile --windowed --name aurachat_helper_arm64

      - name: Clean before next build
        run: rm -rf build dist __pycache__

      - name: Build macOS x86_64 (Intel)
        run: |
          ARCHFLAGS='-arch x86_64' pyinstaller src/aurachat_helper_app/main.py --onefile --windowed --name aurachat_helper_x86_64

      - name: Upload macOS Builds
        uses: actions/upload-artifact@v4
        with:
          name: aurachat_helper-mac
          path: |
            dist/aurachat_helper_arm64
            dist/aurachat_helper_x86_64

  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: aurachat_helper-windows
          path: ./dist/

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: aurachat_helper-mac
          path: ./dist/

      - name: Check contents of dist folder
        run: |
          ls -l ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Aurachat Helper"
          tag_name: "v0.1.11"
          files: |
            ./dist/aurachat_helper.exe
            ./dist/aurachat_helper_arm64
            ./dist/aurachat_helper_x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
