name: Build Tkinter App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r ../requirements.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update Environment Config
        run: python build_script.py
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          ONLYFANSAPI_KEY: ${{ secrets.ONLYFANSAPI_KEY }}
          ENVIRONMENT: "production"

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile --windowed aurachat_helper_app/main.py --name aurachat_helper
          dir dist  # Check if the binary is in dist directory

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: aurachat_helper-windows
          path: src/dist/aurachat_helper.exe
          permissions: 0755

  build-mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r ../requirements.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update Environment Config
        run: python build_script.py
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          ONLYFANSAPI_KEY: ${{ secrets.ONLYFANSAPI_KEY }}
          ENVIRONMENT: "production"

      - name: Build macOS ARM64 App
        run: |
          ARCHFLAGS="-arch arm64" pyinstaller --windowed aurachat_helper_app/main.py --name "Aurachat Helper" --target-arch arm64
          chmod +x "dist/Aurachat Helper.app/Contents/MacOS/Aurachat Helper"
          # Create zip to preserve permissions
          cd dist && zip -r aurachat_helper_arm64.zip "Aurachat Helper.app"
          ls -al

      - name: Clean build files
        run: |
          rm -rf build *.spec
          rm -rf "dist/Aurachat Helper.app"
          mkdir -p dist_temp
          mv dist/aurachat_helper_arm64.zip dist_temp/
          rm -rf dist
          mkdir dist
          mv dist_temp/aurachat_helper_arm64.zip dist/
          rm -rf dist_temp

      - name: Build macOS Intel App
        run: |
          ARCHFLAGS="-arch x86_64" pyinstaller --windowed aurachat_helper_app/main.py --name "Aurachat Helper" --target-arch x86_64
          chmod +x "dist/Aurachat Helper.app/Contents/MacOS/Aurachat Helper"
          # Create zip to preserve permissions
          cd dist && zip -r aurachat_helper_intel.zip "Aurachat Helper.app"
          ls -al

      - name: Upload macOS Builds
        uses: actions/upload-artifact@v4
        with:
          name: aurachat_helper-mac
          path: |
            src/dist/aurachat_helper_arm64.zip
            src/dist/aurachat_helper_intel.zip
          permissions: 0755

  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: aurachat_helper-windows
          path: ./dist/

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: aurachat_helper-mac
          path: ./dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Aurachat Helper"
          tag_name: "v0.1.14"
          files: |
            ./dist/aurachat_helper.exe
            ./dist/aurachat_helper_arm64.zip
            ./dist/aurachat_helper_intel.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
