name: Build Tkinter App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r ../requirements.txt  # Since requirements.txt is one level up
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile --windowed aurachat_helper_app/main.py  # Correct relative path from src/
          dir dist  # Check if the binary is in dist directory

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: aurachat_helper-windows
          path: src/dist/main.exe  # Path to the .exe after the build

  build-mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r ../requirements.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build macOS Binary
        run: |
          pyinstaller --onefile --windowed aurachat_helper_app/main.py
          ls -al dist  # Works on macOS

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: aurachat_helper-mac
          path: src/dist/main  # Ensure this path is correct

  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: aurachat_helper-windows
          path: ./dist/

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: aurachat_helper-mac
          path: ./dist/
      - name: Check contents of dist folder
        run: |
          ls -l ./dist  # Check if the binary is downloaded correctly
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Aurachat Helper"
          tag_name: "v0.1.8"
          files: ./dist/main.exe,./dist/main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
