name: Build Tkinter App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r ../requirements.txt

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile --windowed aurachat_helper_app/main.py
          dir dist  # Use dir for Windows to check contents

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: aurachat_helper-windows
          path: dist/main.exe  # Ensure this path is correct

  build-mac:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r ../requirements.txt

      - name: Build macOS Binary
        run: |
          pyinstaller --onefile --windowed aurachat_helper_app/main.py
          ls -al dist  # Works on macOS

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: aurachat_helper-mac
          path: src/dist/main  # Ensure this path is correct

  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: aurachat_helper-windows
          path: ./dist/

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: aurachat_helper-mac
          path: ./dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Aurachat Helper v0.1.2"
          tag_name: "v0.1.2"
          files: |
            dist/main.exe
            dist/main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
